// GENERATED by scripts/write-build-stamp.mjs on every `npm run build`.
// Do not edit by hand: the next build overwrites it. It is committed with
// `commitSha: null` so a checkout never claims a build it did not make;
// `null` is the explicit "this build is unstamped" marker, which
// src/release-build-match.js turns into the `unknown` verdict `/healthz`
// reports with reason `no_build_stamp`.
export const BUILD_STAMP = Object.freeze({
  schemaVersion: 1,
  commitSha: "b80f91c008d632397f0eb58e0ecc75aff3aeaef7",
  commitSubject: "Agent: Use one name for the invented example records on the homepage and Releases (#2536)",
  builtAt: "2026-09-25T07:38:14.797Z",
});

export default BUILD_STAMP;
