// GENERATED by scripts/write-build-stamp.mjs on every `npm run build`.
// Do not edit by hand: the next build overwrites it. It is committed with
// `commitSha: null` so a checkout never claims a build it did not make;
// `null` is the explicit "this build is unstamped" marker, which
// src/release-build-match.js turns into the `unknown` verdict `/healthz`
// reports with reason `no_build_stamp`.
export const BUILD_STAMP = Object.freeze({
  schemaVersion: 1,
  commitSha: "d887e1b3d984af249c526d7562ab86121042d07d",
  builtAt: "2026-09-04T14:54:36.481Z",
});

export default BUILD_STAMP;
