// GENERATED by scripts/write-build-stamp.mjs on every `npm run build`.
// Do not edit by hand: the next build overwrites it. It is committed with
// `commitSha: null` so a checkout never claims a build it did not make;
// `null` is the explicit "this build is unstamped" marker, which
// src/release-build-match.js turns into the `unknown` verdict `/healthz`
// reports with reason `no_build_stamp`.
export const BUILD_STAMP = Object.freeze({
  schemaVersion: 1,
  commitSha: "46a241a0f684a0b8b5490c4ff990b691df7cf4e0",
  builtAt: "2026-09-04T14:33:13.147Z",
});

export default BUILD_STAMP;
